#!/usr/bin/env node
// Registry of customer source documents (TOR, Excel, Word, review notes...).
// Machine record: .mflow/sources.json   Human view: <sourceDir>/INDEX.md (generated)
//
//   node source-index.mjs scan                       -> JSON: new / changed / unchanged / missing
//   node source-index.mjs mark <file...> [--status active|superseded|reference]
//        [--by <replacing file>] [--used-by <hs-slug|change|review>] [--note "..."] [--title "..."]
//   node source-index.mjs render                     -> regenerate INDEX.md
//
// A file counts as "processed" once it has been marked. Editing a file changes its hash,
// so it shows up as "changed" and must be re-read.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { findRoot, loadConfig } from "./lib.mjs";

const root = findRoot(process.env.CLAUDE_PROJECT_DIR || process.cwd()) || process.cwd();
const cfg = loadConfig(root);
const sourceDir = cfg.sourceDir || "docs/source";
const absSource = path.join(root, sourceDir);
const dbFile = path.join(root, ".mflow", "sources.json");
const SKIP = new Set(["INDEX.md", "README.md", ".gitkeep"]);

const toPosix = (p) => p.split(path.sep).join("/");
const loadDb = () => {
  try { return JSON.parse(fs.readFileSync(dbFile, "utf8")); } catch { return { version: 1, files: {} }; }
};
const saveDb = (db) => {
  fs.mkdirSync(path.dirname(dbFile), { recursive: true });
  fs.writeFileSync(dbFile, JSON.stringify(db, null, 2) + "\n");
};
const sha = (file) => crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex").slice(0, 16);

function listFiles(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".")) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...listFiles(full));
    else if (!SKIP.has(e.name) || dir !== absSource) out.push(full);
  }
  return out;
}

export function scan() {
  const db = loadDb();
  const seen = new Set();
  const result = { sourceDir, new: [], changed: [], unchanged: [], missing: [] };
  for (const full of listFiles(absSource)) {
    const rel = toPosix(path.relative(root, full));
    seen.add(rel);
    const rec = db.files[rel];
    const hash = sha(full);
    if (!rec) result.new.push(rel);
    else if (rec.hash !== hash) result.changed.push({ file: rel, status: rec.status });
    else result.unchanged.push({ file: rel, status: rec.status });
  }
  for (const rel of Object.keys(db.files)) if (!seen.has(rel)) result.missing.push(rel);
  return result;
}

function render() {
  const db = loadDb();
  const rows = Object.entries(db.files).sort(([a], [b]) => a.localeCompare(b));
  const cell = (v) => String(v ?? "").replaceAll("|", "\\|");
  const lines = [
    "# Source documents",
    "",
    "<!-- Generated by mflow (scripts/source-index.mjs). Edit through /mflow:source, not by hand.",
    "     Originals in this folder are never edited: a new version is a new file. -->",
    "",
    "| File | Title | Status | Replaced by | Used by | Processed | Note |",
    "|---|---|---|---|---|---|---|",
    ...rows.map(([f, r]) =>
      `| ${cell(f)} | ${cell(r.title)} | ${cell(r.status)} | ${cell(r.supersededBy)} | ${cell((r.usedBy || []).join(", "))} | ${cell(r.processedAt)} | ${cell(r.note)} |`),
    "",
  ];
  fs.mkdirSync(absSource, { recursive: true });
  fs.writeFileSync(path.join(absSource, "INDEX.md"), lines.join("\n"));
}

function mark(argv) {
  const files = [];
  const opts = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) opts[a.slice(2)] = argv[++i];
    else files.push(toPosix(path.relative(root, path.resolve(root, a))));
  }
  if (!files.length) throw new Error("mark: give at least one file");
  const db = loadDb();
  const today = new Date().toISOString().slice(0, 10);
  for (const rel of files) {
    const full = path.join(root, rel);
    if (!fs.existsSync(full)) throw new Error(`mark: not found: ${rel}`);
    const rec = db.files[rel] || { status: "active", usedBy: [] };
    rec.hash = sha(full);
    rec.processedAt = today;
    if (opts.status) rec.status = opts.status;
    if (opts.by) {
      rec.status = "superseded";
      rec.supersededBy = toPosix(path.relative(root, path.resolve(root, opts.by)));
    }
    if (opts["used-by"] && !rec.usedBy.includes(opts["used-by"])) rec.usedBy.push(opts["used-by"]);
    if (opts.note) rec.note = opts.note;
    if (opts.title) rec.title = opts.title;
    db.files[rel] = rec;
  }
  saveDb(db);
  render();
  return { marked: files };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const [cmd, ...rest] = process.argv.slice(2);
  try {
    let out;
    if (cmd === "scan") out = scan();
    else if (cmd === "mark") out = mark(rest);
    else if (cmd === "render") { render(); out = { rendered: `${sourceDir}/INDEX.md` }; }
    else throw new Error("usage: source-index.mjs scan | mark <file...> [options] | render");
    process.stdout.write(JSON.stringify(out, null, 2) + "\n");
  } catch (err) {
    process.stderr.write(String(err.message || err) + "\n");
    process.exit(1);
  }
}
